name: aqs_client_space
description: Mobile Application for Algerian Qatari Steel Clients.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.1
  intl: ^0.16.1
  http: ^0.12.2
  carousel_slider: ^2.2.1
  step_progress_indicator: ^0.2.3+6
  shared_preferences: ^0.5.8
  progress_dialog: ^1.2.4
  url_launcher: ^5.1.2
  auto_size_text: ^2.1.0
  email_validator: ^1.0.0
  regexed_validator: ^1.0.4
  flutter_launcher_icons: ^0.8.0
  flutter_launcher_name: ^0.0.1
  fluttertoast: ^7.1.1
  progress_state_button: ^1.0.1
  font_awesome_flutter: ^8.8.1
  date_format: ^1.0.9
  flutter_svg: ^0.19.0
  pdf: ^1.11.2
  path_provider: ^1.6.18
  printing: ^3.6.1
  flutter_slidable: ^0.5.7
  gradient_app_bar: ^0.1.3
  local_auth: ^0.6.3+4
  syncfusion_flutter_datagrid: ^18.3.35-beta
  syncfusion_flutter_calendar: ^18.3.35
  syncfusion_flutter_datepicker: ^18.3.35-beta
  syncfusion_flutter_charts: ^18.3.35
  syncfusion_flutter_gauges: ^18.3.35
  syncfusion_flutter_sliders: ^18.3.35-beta
  syncfusion_flutter_pdf: ^18.3.35-beta
  syncfusion_flutter_barcodes: ^18.3.35
  syncfusion_officechart: ^18.3.35-beta
  syncfusion_flutter_maps: ^18.3.35-beta
  syncfusion_flutter_signaturepad: ^18.3.35-beta
  syncfusion_flutter_pdfviewer: ^18.3.35-beta

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/AqsClient_logo.png"

flutter_launcher_name:
  name: "AQS Client Space"

# run the following cmd to override name and icons => flutter pub run flutter_launcher_icons:main
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/
      # - assets/images/logo.png
      # - assets/images/small_logo.png
      # - assets/images/order.png
      # - assets/images/ticket.png
      # - assets/images/ringaqs.gif
      # - assets/images/facture.png
      # - assets/images/order.png
      # - assets/images/sold.png
      # - assets/images/Logo_AQS_3.png
      # - assets/images/logout.png
      # - assets/images/aboutus.png
      # - assets/images/about_us.png
      # - assets/images/001.png
      # - assets/images/home.png
      # - assets/images/fb.png
      # - assets/images/AqsClient_logo.png
      # - assets/images/warning.png
      # - assets/images/nodata.png
      # - assets/images/client_avatar.png
      # - assets/images/menu.svg
      # - assets/images/search.svg
      # - assets/images/fm.jpg
      # - assets/images/rb.png
      # - assets/images/aqs-qr-code.png
      # - assets/images/return.png
      # - assets/images/delivery.png
      # - assets/images/money.png
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: OpenSans
        fonts:
          - asset: assets/fonts/OpenSans-Regular.ttf
          - asset: assets/fonts/OpenSans-Bold.ttf
            weight: 700
      - family: Quicksand
        fonts:
          - asset: assets/fonts/Quicksand-Regular.ttf
          - asset: assets/fonts/Quicksand-Bold.ttf
            weight: 700
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
